USE ultraschall;
GO
IF OBJECT_ID(N'podcasts', N'U') IS NOT NULL
BEGIN
  DROP TABLE podcasts;
END
GO
CREATE TABLE podcasts
(
  id UNIQUEIDENTIFIER DEFAULT NEWID(),
  title NVARCHAR(256) NOT NULL,
  subtitle NVARCHAR(256),
  description NVARCHAR(256) NOT NULL,
  summary NVARCHAR(256),
  language NVARCHAR(8) NOT NULL,
  link NVARCHAR(512) NOT NULL,
  image NVARCHAR(512) NOT NULL,
  owner UNIQUEIDENTIFIER NOT NULL REFERENCES contributor(id) ON DELETE CASCADE
)
GO

